### ISSUE TITLE
Accept Data To Post

### ISSUE THREAD

**Issue by thealphadollar** [oss2019/naarad#20]
Create a function to ask the user to add details which need to be posted in the group(s).

We will be accepting the following information to begin with:

- Description
- Image Path (optional)
- List of groups (comma separated)

These should be stored in a single session of the script inside Facebook class.

**Comment by iharshit009** [comment]
sir we have to do #5 or this one #20 ??

**Comment by thealphadollar** [comment]
This one.

**Comment by iharshit009** [comment]
Sir i am getting the issue in giving the path of image...??
Could you give in a hint?

this is a piece of code for image path
def image(self):
        inputs = self.driver.find_elements_by_tag_name('input')
        for i in inputs:
            if i.text == 'Photo/Video':
                i.click()
        path = input("please tell the full path of Image/Video: ")
        time.sleep(5)
        actions = ActionChains(self.driver)
        actions.move_to_element('File name:').send_keys(path).perform()  # I am getting an error in this line..

**Comment by thealphadollar** [comment]
What issue are you facing?

Ask the user to provide a path  to the image file; it'll be a normal string.
