### ISSUE TITLE
Sanitize Group links

### ISSUE THREAD

**Issue by thealphadollar** [oss2019/naarad#22]
The group link may contain whitespace due to user not being able to decide whether to put space after / before comma or not.

We should make sure the links do not contain whitespace.

https://github.com/oss2019/naarad/blob/72acc72c13dfe382d842ee614f60062df6ba4876/src/main.py#L36

**Comment by iharshit009** [comment]
okk sir

**Comment by iharshit009** [comment]
sorry sir i could not understand about this issue??
i mean if user inputs the following the result would be same and will open the group page...
1) "https://www.facebook.com/groups/DevCIndore"
2) "https://www.facebook.com/groups/DevCIndore/"
3) "https://www.facebook.com/groups/DevCIndore/       "
4) "https://www.facebook.com/groups/DevCIndore    "

**Comment by thealphadollar** [comment]
Yes, but what about " https://www.facebook.com/groups/DevCIndore".

Apart from this, we want to store it in an appropriate manner in order to avoid any complications.
