### ISSUE TITLE
Decide Technologies To Use

### ISSUE THREAD

**Issue by thealphadollar** [oss2019/naarad#3]
We will be using methods such as scraping, web automation driving and form submission.

Selenium and beautifulsoup4 are two of the most known technologies but it is good for a student to do a research of the technologies and then give a report.

**Comment by iharshit009** [comment]
can we use microsoft flow for automation??

**Comment by thealphadollar** [comment]
> can we use microsoft flow for automation??

Hey Harshit, AFAIK Microsoft flow provides task automation but here we use the term automation for the process that the user gives the content and list of links and we **automate** the process of posting it in various groups. Therefore, there is no use of flow here IMO.

It is great that you are finding new technologies to work with :sparkles:
