### ISSUE TITLE
Accept Input From The User

### ISSUE THREAD

**Issue by thealphadollar** [oss2019/naarad#5]
Make a function that accepts the three inputs from the user:

- Phone Number / Email
- Password
- List of group links (or names)

The password should be stored after [encrypting it](https://stackoverflow.com/questions/157938/hiding-a-password-in-a-python-script-insecure-obfuscation-only) on the user's system the first time he uses the application and after that, we should use the file unless it's not available or has been deleted.

**Comment by iharshit009** [comment]
Sir did you mean this one??

**Comment by thealphadollar** [comment]
#15 <- this issue.
