### ISSUE TITLE
Selenium Setup For Facebook Login

### ISSUE THREAD

**Issue by thealphadollar** [oss2019/naarad#6]
A function that takes as arguments the username and password of the user and logins him into facebook using the WebDriver we will be using (most probably Selenium).

Resources:
- https://crossbrowsertesting.com/blog/test-automation/automate-login-with-selenium/

**Comment by iharshit009** [comment]
I would like to take up this issue and work on it.. Should I procede??

**Comment by thealphadollar** [comment]
Yes, please.

I would also request you to join the communication channel on gitter.

**Comment by iharshit009** [comment]
I have joined it sir.

**Comment by thealphadollar** [comment]
You can begin working on this; I'm adding the instructions on how to set up the development environment within the next 5 minutes.

**Comment by iharshit009** [comment]
great sir

**Comment by thealphadollar** [comment]
I've updated the development instructions, please have a look and notify me if you need help with anything.

**Comment by iharshit009** [comment]
hi sir I have made this issue complete.
Please guide me where to upload the file??

**Comment by thealphadollar** [comment]
Hey @iharshit009 , you can use git to update the repository and create a pull request.

If you are not familiar with git, please use [this tutorial](https://www.codecademy.com/learn/learn-git) and make yourself at home with git and then upload the work you've done on the issue. Feel free to approach me for further help :)

**Comment by iharshit009** [comment]
Sir Please check the PR ...

**Comment by thealphadollar** [comment]
fixed in #10
